### ISSUE TITLE
potential parameter typo

### ISSUE THREAD

**Issue by hkaraoguz** [easternRainy/MSDS-DL-Final-YOLO-Implement#1]
https://github.com/easternRainy/YOLO-Implement/blob/6bc341a6744a9598ed0368186321c6d175515ab6/yolo.py#L104

Should 496 be 4096 instead?

**Comment by easternRainy** [comment]
Yes. In the original paper 4096. I made it smaller to run on local laptop. Thank you!

Sent with a Spark
